name: Rust

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        curl -LO https://github.com/YOU54F/hello_cli/releases/download/v0.0.0/pact_cli_x86_64-linux-musl
        chmod +x pact_cli_x86_64-linux-musl
        ./pact_cli_x86_64-linux-musl --help
        
